 # Use the first example from https://circleci.com/docs/2.0/getting-started/
 version: 2
 jobs:
   build:
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - run: foobar