 # Use the first example from https://circleci.com/docs/2.0/getting-started/
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: mkdir -p src
      - run: echo "hello world, again" > src/hello
      - persist_to_workspace:
          root: src
          paths:
            - hello
  test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - attach_workspace:
          at: src
      - run: |
          if [[ $(cat src/hello) == "hello world, again" ]]; then
            echo "woo";
          else
            echo "fi ends if, amazing. also you failed"; exit 123
          fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build