 # Use the first example from https://circleci.com/docs/2.0/getting-started/
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: mkdir -p src
      - add_ssh_keys:
          fingerprints:
            - "df:6f:f2:88:cf:aa:59:46:bf:23:bc:37:8a:1f:45:62"
      - run: git clone https://github.com/bwdGitHub/dummy.git src
      - run: mkdir -p test
      - checkout:
          path: test
      - run: python -m unittest test/test_foo.py
