 # Use the first example from https://circleci.com/docs/2.0/getting-started/
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run: mkdir -p src
      - run: git clone git@github.com:bwdGitHub/dummy.git src
      - run: echo "yay - cloned separate repo"
      - run: mkdir -p test
      - checkout:
          path: test
